# .github/workflows/daily-commit.yml
name: Daily Commit

on:
  schedule:
    - cron: "0 0,10,20 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    permissions: # Otorga los permisos para el flujo de trabajo - Esto es necesario para crear un commit
      issues: write
      pull-requests: write
      contents: write

    steps:
      - uses: actions/checkout@v2

      - name: Set up Git credentials
        run: |
          git config --global user.name "vivz-dev"
          git config --global user.email "vivianavera03@gmail.com"
          git remote set-url origin https://${{ secrets.AI_Artwork }}@github.com/vivz-dev/repo.git

      - name: Run script
        run: |
          chmod +x ./.github/scripts/auto_commit.sh
          bash ./.github/scripts/auto_commit.sh
